### ISSUE TITLE
How to simulation with Gd2(SO4)3 salt dissolved in water?

### ISSUE THREAD

**Issue by tuankhaibui** [WCSim/WCSim#343]
Hi, 
I want to make some simulation with Gd2(SO4)3 salt dissolved in water. 
For example, I want to test with different concentration of Gd (0.2%, 0.4%, 0.6%, ...) in water and investigate WC performance. 
What parameters should I change?

**Comment by tdealtry** [comment]
Hello @tuankhaibui 
In this main WCSim, we don't have those options (quite yet). However if you look in the nuPRISM/develop branch of nuPRSIM/WCSim, there are [parameters you can play around with ](https://github.com/nuPRISM/WCSim/blob/nuPRISM/develop/WCSim.mac#L22)

**Comment by tuankhaibui** [comment]
thanks Thomas @tdealtry 
I may try to "run before I can walk". 
May I ask how to set up geant4 for this WCSim? 
What geant4 version should I use?

**Comment by tuankhaibui** [comment]
Is there anyone tested with geant4.10 ? 
I saw the documents here only mention geant4.9.4

**Comment by tdealtry** [comment]
Sorry for the delay @tuankhaibui 
This code (the develop branch, and latest release) is known to work with 4.10.1.3. This is the officially supported version (sorry that the README is unclear - new version coming soon)
It also works with 4.10.3.3 (just a minor change required in one file - the compilation error should be obvious), and sees consistent results with 4.10.1.3 in places that have been studied (with the additional benefit that radioactive multi-gamma decay is correct). This version will soon be the officially supported version
FYI the nuPRISM/develop branch requires 4.10.3.3
